admin_user_id: "" # 管理员用户 ID
temp_folder: "utils/temp"

server:
  host: "127.0.0.1"
  port: 5888

qq:
  admin_qq: "" # QQ管理员用户 ID
  bot_qq: "" # QQ机器人账号
  bot_name: "amer"

yh:
  admin_id: "" # 云湖管理员用户 ID
  token: "" # 云湖机器人 token
  mode: "websocket" # 接收模式: "webhook" 或 "websocket"
  webhook:
    path: "/yh/webhook"
  websocket:
    url: "wss://ws.jwzhd.com/subscribe?token="

redis:
  host: "127.0.0.1"
  port: 6379
  db: 14
  password: ""

sqlite:
  db_path: "utils/sqlite/amer.db"

blocked_words:
  测试: ["123", "nh"]


messages:
  message_yh: "**指令说明**\n\n1. **/绑定 <QQ群号>**\n   - **功能**: 将当前云湖群与指定的QQ群进行绑定。\n\n2. **/同步模式 <全同步 / 停止 / QQ到云湖 / 云湖到QQ> [可选:QQ群]**\n   - **功能**: 切换消息同步模式，支持多向同步、单向同步（云湖到QQ、QQ到云湖）和停止同步。\n\n3. **/解绑 <QQ群号 / 全部>**\n   - **功能**: 取消与指定QQ群的绑定，输入“全部”时取消所有绑定。\n---\n**注意**: 操作教程需在机器人私聊中使用 `/帮助` 指令。\n - **全体消息自动加到绑定群聊的看板**: 所有消息会自动添加到绑定群聊的看板中，方便查看和管理。"
  message_yh_followed: "# 欢迎使用Amer-Link!\n\n**简介**\n- Amer机器人用于在云湖群和QQ群之间同步消息。请注意，您无法在当前页面使用绑定指令。\n\n**功能更新**\n- **单向消息同步**: 消息可以从云湖单向同步到QQ群或从QQ群单向同步到云湖。\n- **双向消息同步**: 消息可以在云湖和QQ群之间双向同步。\n- **其它同步**: 图片、表情包、视频、部分分享内容等也可以在云湖和QQ群之间同步。\n\n**如何使用**\n1. **添加Amer至群聊**: 确保将Amer添加至您的QQ群和云湖群。[点击此处添加QQ-Amer](https://qm.qq.com/cgi-bin/qm/qr?k=gTDGvgdLBBoZ18x2uXJHm28xFpwcJdWm)\n2. **在云湖端操作**: 在云湖群中绑定您的QQ群，以便开始消息同步。当云湖群绑定QQ群时，QQ群中会提示“此群被云湖绑定了”。\n3. **选择同步模式**: 根据您的需求选择单向或多向消息同步。\n\n**注意**: 指令详情请在云湖群中使用 `/帮助` 指令查看。\n\n如果想请我喝奶茶,[点我赞助](https://ifdian.net/a/YingXinche) **以下是指令说明**\n\n1. **/绑定 <QQ群号>**\n   - **功能**: 将当前云湖群与指定的QQ群进行绑定。\n\n2. **/同步模式 <全同步 / 停止 / QQ到云湖 / 云湖到QQ> [可选:QQ群]**\n   - **功能**: 切换消息同步模式，支持多向同步、单向同步（云湖到QQ、QQ到云湖）和停止同步。\n\n3. **/解绑 <QQ群号 / 全部>**\n   - **功能**: 取消与指定QQ群的绑定，输入“全部”时取消所有绑定。\n---\n**注意**: 操作教程需在机器人私聊中使用 `/帮助` 指令。\n - **全体消息自动加到绑定群聊的看板**: 所有消息会自动添加到绑定群聊的看板中，方便查看和管理。"
