package message

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
	"testing"
)

type qfaceItem struct {
	QSid     string `json:"QSid"`
	QDes     string `json:"QDes"`
	IsStatic string `json:"isStatic"`
}

type qfaceIndexItem struct {
	EmojiID  string `json:"emojiId"`
	Describe string `json:"describe"`
}

func TestGenerateFaceGo(t *testing.T) {
	faceMap := make(map[int]string)

	// 1. Read lib/data.json
	dataPath := filepath.Join("..", "..", "SnowLuma-main", "QFace-master", "QFace-master", "lib", "data.json")
	if _, err := os.Stat(dataPath); os.IsNotExist(err) {
		t.Skip("Skipping generator test: QFace data.json not found")
	}
	if dataBytes, err := os.ReadFile(dataPath); err == nil {
		var items []qfaceItem
		if err := json.Unmarshal(dataBytes, &items); err == nil {
			for _, item := range items {
				id, err := strconv.Atoi(item.QSid)
				if err != nil {
					continue
				}
				name := strings.TrimPrefix(item.QDes, "/")
				if name != "" {
					faceMap[id] = name
				}
			}
		}
	}

	// 2. Read public/assets/qq_emoji/_index.json
	indexPath := filepath.Join("..", "..", "SnowLuma-main", "QFace-master", "QFace-master", "public", "assets", "qq_emoji", "_index.json")
	if indexBytes, err := os.ReadFile(indexPath); err == nil {
		var indexItems []qfaceIndexItem
		if err := json.Unmarshal(indexBytes, &indexItems); err == nil {
			for _, item := range indexItems {
				id, err := strconv.Atoi(item.EmojiID)
				if err != nil {
					continue
				}
				name := strings.TrimPrefix(item.Describe, "/")
				if name != "" && faceMap[id] == "" {
					faceMap[id] = name
				}
			}
		}
	}

	// Check if 344 is in faceMap
	if name, ok := faceMap[344]; !ok || name != "大怨种" {
		t.Fatalf("Expected face 344 to be 大怨种, got: %s (ok=%v)", name, ok)
	}

	var ids []int
	for id := range faceMap {
		ids = append(ids, id)
	}
	sort.Ints(ids)

	var sb strings.Builder
	sb.WriteString("// Code generated by face_gen_test.go; DO NOT EDIT.\n\n")
	sb.WriteString("package message\n\n")
	sb.WriteString("import (\n\t\"fmt\"\n)\n\n")
	sb.WriteString("// qqFaceMap maps QQ Face ID (from OneBot [CQ:face,id=...]) to Chinese face name.\n")
	sb.WriteString("var qqFaceMap = map[string]string{\n")

	for _, id := range ids {
		sb.WriteString(fmt.Sprintf("\t%q: %q,\n", strconv.Itoa(id), faceMap[id]))
	}
	sb.WriteString("}\n\n")

	sb.WriteString(`// GetQQFaceName returns the human-readable name of a QQ face ID (e.g. "大怨种" for "344").
// Returns empty string if unknown.
func GetQQFaceName(faceID string) string {
	return qqFaceMap[faceID]
}

// ParseQQFace parses a QQ face ID into a natural language bracketed string, e.g. "[大怨种]".
// If the ID is unknown, it returns "[表情:ID]".
func ParseQQFace(faceID string) string {
	if name, ok := qqFaceMap[faceID]; ok && name != "" {
		return fmt.Sprintf("[%s]", name)
	}
	if faceID == "" {
		return "[表情]"
	}
	return fmt.Sprintf("[表情:%s]", faceID)
}

// FormatQQFaceHTML returns an HTML representation for Yunhu HTML messages.
// It renders an inline image with alt fallback.
func FormatQQFaceHTML(faceID string) string {
	name, ok := qqFaceMap[faceID]
	if !ok || name == "" {
		if faceID == "" {
			return "[表情]"
		}
		return fmt.Sprintf("[表情:%s]", faceID)
	}
	return fmt.Sprintf("<img src=\"https://koishi.js.org/QFace/static/s%s.png\" alt=\"[%s]\" title=\"%s\" style=\"width:24px;height:24px;vertical-align:middle;display:inline-block;margin:0 2px;\">", faceID, name, name)
}
`)

	outPath := "face.go"
	if err := os.WriteFile(outPath, []byte(sb.String()), 0644); err != nil {
		t.Fatalf("Failed to write face.go: %v", err)
	}
	t.Logf("Successfully generated face.go with %d face definitions!", len(ids))
}
